#!/bin/bash


cd "$(dirname "$0")"
WD="$(pwd)"

read -p "Press enter to start"
while :
do
    read -ra args -p "Enter Args: "
    find . | grep -E "(__pycache__|\.pyc|\.pyo$)" | xargs rm -rf
    clear
    
    "${WD%/*}/.venv/bin/python" "${WD%/*}/dfctl" "${args[@]}"

done
