#!/bin/bash

CWD="$(dirname "$0")"
SNAME="dotfiles"

cd "$CWD"
cd ..

# NVIM
tmux new-session -d -s "$SNAME" "tmux rename-window code;\
				nvim ./;\
				tmux kill-ses -t $SNAME"

# RUN
tmux new-window -t "$SNAME" "tmux rename-window runner;\
			    .dev/run;\
			    tmux kill-ses -t $SNAME"

# RANDOM
tmux new-window -t "$SNAME" "bash;\
			    tmux kill-ses -t $SNAME"
